### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by MichaelCSI** [linamoussadek/HotelsApp#1]
# UI/UX

- [x] Change popup to book instead of register/login
- [x] Book room bug after opening book room popup
- [x] Have navigation to different pages: booking, employee
- [x] Employee login with employeeID, as soon as we navigate to the employee page
- [x] Put the criteria in the middle
- [x] Add street to booking popup
- [x] Refresh the results in ResultsGrid as soon as the Search Button is clicked
- [x] Change the overall color
- [x] Fix spacing between hotel bookings on main page, or add divider of some sort

# Backend

*Insert*
- [x] Route: Booking via popup with register info - create person, customer, and booking
- [x] Route: Booking for popup with just ssn create booking, check ssn found (error, see employee login example)

*Set*
- [x] Set booking to canceled/checkedIn for employee portal (and update list UI)

*UI work*

- [x] Use queries to get dropdown info for booking criteria
- [x] Allow user to see the bookings based on criteria - how to fetch criteria in ResultsGrid?
- [x] Allow employees to see bookings and booking archives

**Comment by MichaelCSI** [comment]
All done!
